// flow-typed signature: 067d3474e1295edea31f056a348be5b2
// flow-typed version: <<STUB>>/react-helmet-async_v0.0.5/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-helmet-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-helmet-async' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-helmet-async/es/client' {
  declare module.exports: any
}

declare module 'react-helmet-async/es/constants' {
  declare module.exports: any
}

declare module 'react-helmet-async/es/Dispatcher' {
  declare module.exports: any
}

declare module 'react-helmet-async/es/index' {
  declare module.exports: any
}

declare module 'react-helmet-async/es/Provider' {
  declare module.exports: any
}

declare module 'react-helmet-async/es/server' {
  declare module.exports: any
}

declare module 'react-helmet-async/es/utils' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/client' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/constants' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/Dispatcher' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/index' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/Provider' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/server' {
  declare module.exports: any
}

declare module 'react-helmet-async/lib/utils' {
  declare module.exports: any
}

// Filename aliases
declare module 'react-helmet-async/es/client.js' {
  declare module.exports: $Exports<'react-helmet-async/es/client'>
}
declare module 'react-helmet-async/es/constants.js' {
  declare module.exports: $Exports<'react-helmet-async/es/constants'>
}
declare module 'react-helmet-async/es/Dispatcher.js' {
  declare module.exports: $Exports<'react-helmet-async/es/Dispatcher'>
}
declare module 'react-helmet-async/es/index.js' {
  declare module.exports: $Exports<'react-helmet-async/es/index'>
}
declare module 'react-helmet-async/es/Provider.js' {
  declare module.exports: $Exports<'react-helmet-async/es/Provider'>
}
declare module 'react-helmet-async/es/server.js' {
  declare module.exports: $Exports<'react-helmet-async/es/server'>
}
declare module 'react-helmet-async/es/utils.js' {
  declare module.exports: $Exports<'react-helmet-async/es/utils'>
}
declare module 'react-helmet-async/lib/client.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/client'>
}
declare module 'react-helmet-async/lib/constants.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/constants'>
}
declare module 'react-helmet-async/lib/Dispatcher.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/Dispatcher'>
}
declare module 'react-helmet-async/lib/index.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/index'>
}
declare module 'react-helmet-async/lib/Provider.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/Provider'>
}
declare module 'react-helmet-async/lib/server.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/server'>
}
declare module 'react-helmet-async/lib/utils.js' {
  declare module.exports: $Exports<'react-helmet-async/lib/utils'>
}
